feat: currency rates
Adamant-im/adamant-im pull request #431
Opened 2022-03-30 12:35 UTC by Mansurkhoja

2022-03-31 06:57 UTC, adamant-al commented on src/store/modules/rate/index.js
> +            if (timestamp !== undefined) {
Why are you doing a request if timestamp === undefined?
May be the first line of getHistoryRates — `if (!timestamp) return;`?

2022-03-31 19:54 UTC, MerdyNumber1 commented on src/components/CurrencySwitcher.vue
> +// eslint-disable-next-line no-unused-vars
?

2022-03-31 19:54 UTC, MerdyNumber1 commented on src/filters/currencyAmountWithSymbol.js
> +  } else return ''
Please, use everywhere braces for if-else conditions

2022-04-01 16:40 UTC, martiliones requested changes

2022-04-01 16:40 UTC, martiliones commented on src/assets/stylus/themes/adamant/_inputs.styl
> +.fake-input__label
Why don't you use child selectors everywhere? (`&__label`)

2022-04-01 16:40 UTC, martiliones commented on src/components/SendFundsForm.vue
> +      return currentRate !== undefined ? `${feeRate} ${this.currentCurrency}` : ''
You can check if `currentRate` is undefined right after getting it from the store and immediately return the empty string. E.g.:

```js
const currentRate = this.$store.state.rate.rates[`${this.transferFeeCurrency}/${this.currentCurrency}`]

if (currentRate === undefined) {
  return ''
}

const feeRate = (this.transferFeeFixed * currentRate).toFixed(2)

return feeRate
```

2022-04-01 16:40 UTC, martiliones commented on src/components/SendFundsForm.vue
> +      return currentRate !== undefined ? `${amountRate} ${this.currentCurrency}` : ''
Same as above

2022-04-01 16:40 UTC, martiliones commented on src/filters/currencyAmount.js
> +    return `${formatted}`
The `toFixed` method already returns a string. It should be `return formatted`

2022-04-05 15:53 UTC, martiliones approved these changes

2022-04-06 08:05 UTC, adamant-al approved these changes

2022-04-06 08:07 UTC, merged