change inactive buttons look
Adamant-im/adamant-im pull request #469
Opened 2023-05-15 18:56 UTC by joebrock666

2023-05-18 17:18 UTC, bludnic commented
@joebrock666 check the task https://trello.com/c/DFsBjI1k/333-ui-inactive-buttons

2023-05-19 05:55 UTC, joebrock666 commented
> @joebrock666 check the task https://trello.com/c/DFsBjI1k/333-ui-inactive-buttons

Done

2023-05-19 18:16 UTC, bludnic requested changes

2023-05-19 18:16 UTC, bludnic commented on src/assets/styles/generic/_vuetify.scss
> +    background-color: #eee; // secondary
Use color scheme
map-get($adm-colors, 'color_name_here');

2023-05-19 18:16 UTC, bludnic commented on src/assets/styles/generic/_vuetify.scss
> +    color: #bbdefb !important; // primary2
map-get($adm-colors, 'color_name_here');

2023-05-19 18:16 UTC, bludnic commented on src/assets/styles/generic/_vuetify.scss
> +    background-color: #4a4a4a !important; // regular
map-get($adm-colors, 'color_name_here');

2023-05-19 18:16 UTC, bludnic commented on src/assets/styles/generic/_vuetify.scss
> +    color: #9e9e9e !important; // grey
map-get($adm-colors, 'color_name_here');

2023-05-24 18:46 UTC, bludnic requested changes

2023-05-24 18:46 UTC, bludnic commented on src/assets/styles/generic/_vuetify.scss
> +
The styles affects other buttons with `variant="text"`

![image](https://github.com/Adamant-im/adamant-im/assets/25831507/08bd97c1-75ce-4f24-b844-7a1e701f3809)

You must apply these styles only for `variant="elevated"` which is by default.

See all variants https://vuetifyjs.com/en/api/v-btn/#props-variant

2023-05-24 18:46 UTC, bludnic commented on src/components/LoginPasswordForm.vue
`const isValidForm` is not used anymore. You can remove it

2023-05-31 21:51 UTC, bludnic requested changes

2023-05-31 21:51 UTC, bludnic commented on src/assets/styles/generic/_vuetify.scss
> +  .v-btn--disabled:not(.v-btn--icon):not(.v-btn--flat).v-btn--variant-elevated  {
The button cannot be `flat` and `elevated` at the same time, so I think you can simplify the selector. Same for other selectors below.

```suggestion
  .v-btn--disabled:not(.v-btn--icon).v-btn--variant-elevated  {
```

2023-06-01 17:22 UTC, bludnic approved these changes

2023-06-01 17:23 UTC, merged