fix max amount to the bottom
Adamant-im/adamant-im pull request #473
Opened 2023-05-19 10:39 UTC by joebrock666

2023-05-19 18:12 UTC, bludnic requested changes

2023-05-19 18:12 UTC, bludnic commented on src/components/SendFundsForm.vue
> +          <span class="body-1 a-label-secondary">
The label in floating state is not aligned
![image](https://github.com/Adamant-im/adamant-im/assets/25831507/718b7d6d-8da9-4de6-892b-e2bf658e674f)

2023-05-19 20:50 UTC, joebrock666 commented on src/components/SendFundsForm.vue
> +          <span class="body-1 a-label-secondary">
<img width="353" alt="Screenshot 2023-05-20 at 12 48 09 AM" src="https://github.com/Adamant-im/adamant-im/assets/50330577/bfd9031d-b165-48fc-84e0-a6b81068f23d">
For some reason, I don't have this issue. You just removed the `body-1` class, right?

2023-05-23 20:40 UTC, bludnic approved these changes

2023-05-23 20:40 UTC, merged