Vote for delegates icon for Vote/Downvote
Adamant-im/adamant-im pull request #514
Opened 2023-07-26 13:46 UTC by joebrock666

https://trello.com/c/AA1z69S5

2023-07-26 14:09 UTC, bludnic requested changes

2023-07-26 14:09 UTC, bludnic commented on src/components/NodesTable/NodesTableItem.vue
>          :color="nodeStatusColor"
remove

2023-07-26 14:09 UTC, bludnic commented on src/components/NodesTable/NodesTableItem.vue
> +        :class="`${classes.statusIcon} ${nodeStatusColor}`"
use array

2023-07-26 14:09 UTC, bludnic commented on src/components/NodesTable/NodesTableItem.vue
> +.green {
&__status-icon {
  &--green {
      color: ...
  }
  ...
}

2023-07-26 14:09 UTC, bludnic commented on src/components/NodesTable/NodesTableItem.vue
> +  color: rgb(61, 209, 151) !important;
use $adm-colors

2023-07-26 14:09 UTC, bludnic commented on src/components/NodesTable/NodesTableItem.vue
> +  color: rgb(237, 82, 112) !important;
use $adm-colors

2023-07-26 14:09 UTC, bludnic commented on src/components/NodesTable/NodesTableItem.vue
> +  color: #9e9e9e !important;
use $adm-colors

2023-07-26 14:09 UTC, bludnic commented on src/components/NodesTable/NodesTableItem.vue
> +  color: rgb(248, 160, 97) !important;
use $adm-colors

2023-07-26 14:09 UTC, bludnic commented on src/components/NodesTable/NodesTableItem.vue
> +.green {
create same selector in .v-theme--light and .v-theme--dark

2023-07-26 16:08 UTC, bludnic requested changes

2023-07-26 16:08 UTC, bludnic commented on src/components/NodesTable/NodesTableItem.vue
> +    }
Remove this. You must specify colors only in `.v-theme--light` and `.v-theme--dark` selectors.

2023-07-26 16:08 UTC, bludnic commented on src/components/NodesTable/NodesTableItem.vue
> +        :class="socketSupport ? `${classes.statusIcon}--green` : `${classes.statusIcon}--red`"
Define class modifiers below in the `const classes`.

```js
    const classes = {
      // ...
      statusIcon: `${className}__status-icon`,
      statusIconGreen: `${className}__status-icon--green`,
      statusIconRed: `${className}__status-icon--red`,
      // ...
    }
```

2023-07-26 16:08 UTC, bludnic commented on src/components/NodesTable/NodesTableItem.vue
> +        :class="[classes.checkbox, `${classes.statusIcon}--grey`]"
:class="[classes.checkbox, classes.statusIconGrey]"

2023-07-26 17:36 UTC, bludnic requested changes

2023-07-26 17:36 UTC, bludnic commented on src/components/NodesTable/NodesTableItem.vue
> +        :class="socketSupport ? `${classes.statusIcon}--green` : `${classes.statusIcon}--red`"
classes.statusIconGreen and classes.statusIconRed

2023-07-26 17:36 UTC, bludnic commented on src/components/NodesTable/NodesTableItem.vue
> +  return color;
```suggestion
  return color
```

2023-07-26 17:36 UTC, bludnic commented on src/components/NodesTable/NodesTableItem.vue
> +    }"
prettify

2023-07-27 00:37 UTC, bludnic commented
@joebrock666 Rollback package-lock.json. Use node v18

2023-07-27 00:37 UTC, bludnic commented on src/components/NodesTable/NodesTableItem.vue
> +        :class="socketSupport ? `${classes.statusIcon}--green` : `${classes.statusIcon}--red`"
not fixed

2023-07-28 11:25 UTC, bludnic commented
There are still changes in the `package-lock.json`. Fix it @joebrock666

2023-07-28 11:57 UTC, joebrock666 commented
> There are still changes in the `package-lock.json`. Fix it @joebrock666

I think now it's the same as in dev

2023-07-28 12:25 UTC, bludnic approved these changes

2023-07-28 12:27 UTC, merged