Feat/ scroll to bottom fab new messages counter
Adamant-im/adamant-im pull request #535
Opened 2023-10-04 03:34 UTC by juliahermak

2023-10-04 03:45 UTC, bludnic requested changes

2023-10-04 03:45 UTC, bludnic commented on src/components/Chat/Chat.vue
> +        <div>
remove div

2023-10-04 03:45 UTC, bludnic commented on src/components/Chat/Chat.vue
> +            :modelValue="numOfNewMessages > 0 ? true : false"
shorter version

```suggestion
            :modelValue="numOfNewMessages > 0"
```

2023-10-04 03:45 UTC, bludnic commented on src/components/Chat/Chat.vue
> +            v-if="!isScrolledToBottom"
I think you can remove `v-if` on `v-badge` component, because it is already used by `v-btn` below.

2023-10-04 03:45 UTC, bludnic commented on src/components/Chat/Chat.vue
> +              :icon="true"
shorter version
```suggestion
              icon
```

2023-10-04 03:45 UTC, bludnic commented on src/components/Chat/Chat.vue
> +              <div><v-icon icon="mdi-chevron-down" size="x-large" /></div>
remove <div/> wrapper

2023-10-04 04:29 UTC, bludnic commented
![](https://github.trello.services/images/mini-trello-icon.png) [Feat: Show new messages count in Chat View FAB](https://trello.com/c/czApsWrP/216-feat-show-new-messages-count-in-chat-view-fab)

2023-10-05 15:54 UTC, adamant-al commented
Doesn't work and style bugs.
https://drive.proton.me/urls/TKP57MWEFG#yZXYadVXV5Gv

2023-10-05 16:04 UTC, bludnic commented
@adamant-al Try to keep the tab hidden until you receive a new message (wait for the sound). This should work.

The counter is not displayed because the tab is visible, so the new message is marked automatically as read regardless of the scroll position. This may be a bug.

2023-10-05 16:24 UTC, adamant-al commented
To test a feature I prefer the bug fix in this PR.

2023-10-05 23:14 UTC, bludnic commented
@adamant-al Bug fixed. Check now

2023-10-06 05:14 UTC, adamant-al commented
The style (padding) bug is still there.

<img width="853" alt="image" src="https://github.com/Adamant-im/adamant-im/assets/33592982/7bd00dee-50ff-4d5d-ae06-1b0d472096d7">

2023-10-06 08:43 UTC, juliahermak commented
@adamant-al Bug fixed. Check now

2023-10-10 08:37 UTC, adamant-al approved these changes

2023-10-10 08:38 UTC, adamant-al commented
@bludnic @martiliones 
Waiting for your review.

2023-10-10 19:59 UTC, bludnic approved these changes

2023-10-10 19:59 UTC, merged