feat: preserve message text in the input field
Adamant-im/adamant-im pull request #537
Opened 2023-10-06 01:46 UTC by juliahermak

2023-10-06 03:09 UTC, bludnic requested changes

2023-10-06 03:09 UTC, bludnic commented on src/components/AChat/AChatForm.vue
> +      if (this.clearInputValueOnSend === true) {
shorter variant
```suggestion
      if (this.clearInputValueOnSend) {
```

2023-10-06 03:09 UTC, bludnic commented on src/components/Chat/Chat.vue
> +          :clearInputValueOnSend="this.$store.state.balance < 0.001 === false"
compare other side with `>=` and use shorter variant

```suggestion
          :clearInputValueOnSend="this.$store.state.balance >= 0.001"
```

2023-10-06 03:09 UTC, bludnic commented on src/components/Chat/Chat.vue
> +          :clearInputValueOnSend="this.$store.state.balance < 0.001 === false"
rename the prop name by using snake-case, just to keep the same style in the codebase

2023-10-06 04:05 UTC, bludnic commented
![](https://github.trello.services/images/mini-trello-icon.png) [Feat: Preserve message text in the input field, if it was not sent](https://trello.com/c/HUvfBtph/363-feat-preserve-message-text-in-the-input-field-if-it-was-not-sent)

2023-10-06 04:23 UTC, bludnic approved these changes

2023-10-06 05:29 UTC, adamant-al requested changes
I don't like the custom-case solution.
We have `validateMessage` method.
Also, consider moving magic numbers to constants.
Refactor code, if appropriate.

2023-10-13 20:26 UTC, bludnic commented
> I don't like the custom-case solution. We have `validateMessage` method. Also, consider moving magic numbers to constants. Refactor code, if appropriate.

I need to think about how to make the validation in one place and share it between Chat and AChatForm component, then I will came with a solution

2023-11-02 01:32 UTC, bludnic commented
- Added `validator` prop for `AChatForm`
- Replaced harcoded fee from constants

@adamant-al

2023-11-02 14:31 UTC, bludnic commented on src/components/Chat/Chat.vue
> +const validationErrors = {
moved above the docblock

2023-11-02 22:21 UTC, merged