feat: beautiful code markdown
Adamant-im/adamant-im pull request #540
Opened 2023-10-09 21:20 UTC by juliahermak

Before:
![Screenshot 2023-10-09 22 15 51](https://github.com/Adamant-im/adamant-im/assets/122323015/9c555498-cf26-41e2-adce-634d1fb8d5b7)
After:
![Screenshot 2023-10-09 22 16 04](https://github.com/Adamant-im/adamant-im/assets/122323015/fd898087-5dc4-4666-b673-d98b60eaca6b)

2023-10-10 14:51 UTC, bludnic commented
![](https://github.trello.services/images/mini-trello-icon.png) [Feat: Beautiful code markdown](https://trello.com/c/b5jkzwzx/381-feat-beautiful-code-markdown)

2023-10-11 03:31 UTC, juliahermak commented
Before:
![Screenshot 2023-10-11 04 23 29](https://github.com/Adamant-im/adamant-im/assets/122323015/5a1da63e-877c-41d9-bc54-d672e806f718)
After:
![Screenshot 2023-10-11 04 23 59](https://github.com/Adamant-im/adamant-im/assets/122323015/f4e71b46-4186-438b-938a-97938aadc082)

2023-10-11 03:31 UTC, bludnic requested changes

2023-10-11 03:31 UTC, bludnic commented on src/assets/styles/components/_chat.scss
> +        color: #ffffff;
```suggestion
        color: map-get($shades, 'white');
```

2023-10-11 03:31 UTC, bludnic commented on src/assets/styles/components/_chat.scss
> +        background-color: map-get($adm-colors, 'secondary2-slightly-transparent') !important;
will it work without `!important`?

2023-10-11 03:31 UTC, bludnic commented on src/assets/styles/components/_chat.scss
> +      code{
```suggestion
      code {
```

run prettier

2023-10-15 10:12 UTC, juliahermak commented
I added all the fonts from this list and added one more at Bludnic request.
![Screenshot 2023-10-15 11 07 18](https://github.com/Adamant-im/adamant-im/assets/122323015/7d4798be-7ecd-4c75-a52a-55463faf460f)

2023-10-15 15:41 UTC, bludnic commented
@martiliones see discussion in trello card. This select was added for testing purposes.

2023-11-03 22:00 UTC, bludnic approved these changes

2023-11-03 22:01 UTC, merged