Feat/update bitcoinjs lib
Adamant-im/adamant-im pull request #544
Opened 2023-10-23 17:51 UTC by RealGoodProgrammer

2023-10-24 10:13 UTC, bludnic commented
![](https://github.trello.services/images/mini-trello-icon.png) [Update bitcoinjs-lib](https://trello.com/c/IO8SGz5y/322-update-bitcoinjs-lib)

2023-10-24 10:39 UTC, bludnic requested changes

2023-10-24 10:39 UTC, bludnic commented on src/lib/bitcoin/btc-base-api.js
> +    // // populate with txHex <--
```suggestion
    // populate unspents with full transaction in HEX
```

2023-10-24 10:39 UTC, bludnic commented on src/lib/bitcoin/btc-base-api.js
> +    // })
comment can be removed

2023-10-24 10:39 UTC, bludnic commented on package-lock.json
> -      "dev": true
Still a lot of changes in `package-lock`. May need to revert the file and install again with node v18.

2023-10-24 18:51 UTC, bludnic requested changes

2023-10-24 18:51 UTC, bludnic commented on package.json
> +    "vite-plugin-wasm": "^3.2.2",
move to `devDependencies`

2023-10-25 16:03 UTC, bludnic approved these changes

2023-10-25 16:29 UTC, merged

2023-10-25 17:57 UTC, adamant-al reviewed
- Try to send txs (including taproot) through `bitcoind`, not an indexer. See 'Expose bitcoind API' https://trello.com/c/Pa45S7nJ (currently btcnode2 only).
Probably, we can switch to `bitcoind` for most requests (except tx history by address). Is it possible to optimize tx creation and don't retrieve hexes for all of unspents with `bitcoind`?

- What's the reason to add two more libs? `ecpair`, `tiny-secp256k1` (`plus vite-plugin-wasm` and `vite-plugin-top-level-await`). Why can't we use `bitcoin.ECPair.fromPrivateKey()`? Doesn't 'bitcoinjs-lib' include `ECPair` or alternative anymore?

2023-10-25 18:00 UTC, adamant-al commented
`export default class DashApi extends BtcBaseApi`
`export default class DogeApi extends BtcBaseApi`

Have you tested DOGE and DASH?

2023-10-25 19:02 UTC, RealGoodProgrammer commented on src/lib/bitcoin/btc-base-api.js
> +          nonWitnessUtxo: Buffer.from(tx.txHex, 'hex')
Yes, it always will be nonWitnessUtxo until we start to supporting BIP84

2023-10-26 14:25 UTC, bludnic commented
> What's the reason to add two more libs? ecpair, tiny-secp256k1 (plus vite-plugin-wasm and vite-plugin-top-level-await). Why can't we use bitcoin.ECPair.fromPrivateKey()? Doesn't 'bitcoinjs-lib' include ECPair or alternative anymore?

The `bitcoinjs-lib` doesn't include ECPair in the new version, so we had to include `ecpair` and `tiny-secp256k1` dependencies (this is what `bitcoinjs-lib` suggested).

Since `tiny-secp256k1` uses WASM, additional Vite plugins are required: `vite-plugin-wasm` and `vite-plugin-top-level-await`). These are devDependencies, so it doesn't affect the bundle size.

2023-10-26 14:31 UTC, bludnic commented
> Is it possible to optimize tx creation and don't retrieve hexes for all of unspents with bitcoind?

We will try.