Release v4.3.0
Adamant-im/adamant-im pull request #548
Opened 2023-11-02 01:41 UTC by bludnic

### Features

- #547
- #535
- #538
- #540

### Teach debt

- #542
- #544
- Update Lisk SDK
- #545

### Fixes

- #534
- #537

2023-11-24 20:56 UTC, RealGoodProgrammer approved these changes

2023-11-25 08:15 UTC, adamant-al requested changes
<img width="860" alt="Screenshot 2023-11-25 в 12 14 54" src="https://github.com/Adamant-im/adamant-im/assets/33592982/cb5d0e88-3036-4267-838b-8e9c7791d994">
<img width="815" alt="Screenshot 2023-11-25 в 12 15 27" src="https://github.com/Adamant-im/adamant-im/assets/33592982/8449a57d-1e3a-4748-8149-53dc3678cd2a">

2023-11-25 17:06 UTC, bludnic commented
@adamant-al reverted the changes https://github.com/Adamant-im/adamant-im/pull/565

2023-11-26 13:15 UTC, adamant-al approved these changes

2023-11-26 13:18 UTC, merged