fix(DOGE/DASH): transfering funds doesn't work after `bitcoinjs-lib` upgrade
Adamant-im/adamant-im pull request #552
Opened 2023-11-06 17:37 UTC by RealGoodProgrammer

2023-11-06 19:47 UTC, bludnic requested changes

2023-11-06 20:36 UTC, bludnic requested changes

2023-11-06 20:36 UTC, bludnic commented on src/lib/bitcoin/dash-api.js
> +  async getTransactionHex(txid) {
Remove async. Its optional.

2023-11-06 20:36 UTC, bludnic commented on src/lib/bitcoin/doge-api.js
> +    const { rawtx } = this._get(`/api/rawtx/${txid}`)
You probably need to `await` here

2023-11-06 20:36 UTC, bludnic commented on src/lib/bitcoin/doge-api.js
> +  }
Can be removed. This function is inherited from btc-base-api

2023-11-07 17:30 UTC, RealGoodProgrammer commented on src/lib/bitcoin/doge-api.js
> +      new BigNumber(currentFeeRate * (estimatedTxBytes + OUTPUTS_COMPENSATION))
I'll leave this unchanged for better readability

2023-11-07 17:50 UTC, RealGoodProgrammer commented on src/lib/bitcoin/doge-api.js
> +    const txb = new bitcoin.Psbt({
I

2023-11-07 17:51 UTC, RealGoodProgrammer commented on src/lib/bitcoin/doge-api.js
> +    const txb = new bitcoin.Psbt({
That means "builder". But you're right, it's more appropriate to call it psbt

2023-11-08 15:52 UTC, bludnic commented on src/lib/bitcoin/doge-api.js
> +      transferAmount += tx.amount
For now I think it's enough to use multiply and divide

2023-11-08 19:04 UTC, bludnic approved these changes

2023-11-09 00:08 UTC, merged

2023-11-09 00:09 UTC, bludnic commented
![](https://github.trello.services/images/mini-trello-icon.png) [Update bitcoinjs-lib](https://trello.com/c/IO8SGz5y/322-update-bitcoinjs-lib)