Decline transaction with same nonce (ETH, ERC20, LSK)
Adamant-im/adamant-im pull request #560
Opened 2023-11-16 18:08 UTC by RealGoodProgrammer

Display an error message when the user tries to send two transactions with equal `nonce`.

The last transaction `nonce` is saved in the `SessionStorage` right before sending the tokens.
Subsequent transactions are checked for the `nonce` equality. If the `nonces` are equal, an error message will be displayed.

In addition to the `nonce` transaction, the `expirationTime` is also saved. In rare situations the transaction may not reach the node (e.g. Network Error). We expect that `nonce` will change but it will not. The `expirationTime` must cover this edge case.

`expirationTime = coin.newPendingAttempts * coin.newPendingInterval`
(the values are taken from [adamant-wallets](https://github.com/Adamant-im/adamant-wallets/blob/master/assets/general/ethereum/info.json#L21))

- For ETH/ERC20: 80s
- For LSK: 45s

![image](https://github.com/Adamant-im/adamant-im/assets/25831507/36871acd-1d5d-4236-a082-78d0e73d1cee)

2023-11-16 18:09 UTC, RealGoodProgrammer commented
![](https://github.trello.services/images/mini-trello-icon.png) [Feat: Decline second crypto transfer if we get same Nonce](https://trello.com/c/HMtWwgV8/369-feat-decline-second-crypto-transfer-if-we-get-same-nonce)

2023-11-19 13:04 UTC, adamant-al requested changes
This PR doesn't resolve the issue.

- You mark if the tx in process locally
- If you send BTC tx and restart the app, it will "think" that there is no pending txs

Consider to check current `nonce` for account.

Blockchains that have `nonce`: LSK, ETH
To research: BTC, DOGE, DASH

2023-11-20 13:54 UTC, RealGoodProgrammer commented on src/store/modules/eth-base/eth-base-actions.js
> +      if (context.state.isTransactionInProcess) return
No, you're both wrong. I just don't want to throw this error twice. Check it for yourself

2023-11-28 11:36 UTC, bludnic commented on src/lib/txVerify.js
> +  const TX_LOCK_TIME = fetchInfo.newPendingAttempts * fetchInfo.newPendingInterval
According to the specification the `txFetchInfo` and its properties are optional. Take this into consideration and perform additional check.

![image](https://github.com/Adamant-im/adamant-im/assets/25831507/c7856ba3-5166-45a8-bef5-bf6586837a1d)

2023-11-28 11:49 UTC, bludnic commented on src/lib/txVerify.js
> +  const expiration = Date.now()
The name is confusing. I suggest to pick another name, e.g. `today`, `currentTimestamp`, or any other more meaningful name at your choice.

2023-11-30 13:37 UTC, bludnic requested changes

2023-11-30 13:37 UTC, bludnic commented on src/lib/errors.js
> +  constructor(message, errorCode) {
Also remove ErrorCodes above

2023-11-30 13:37 UTC, bludnic commented on src/lib/sessionStorage.js
> +export const getFromSessionStorage = (key) => {
Rewrite to TS. An example how to type it properly with generic:
https://github.com/Adamant-im/adamant-im/blob/master/src/lib/nodes/storage.ts#L17

2023-11-30 13:37 UTC, bludnic commented on src/lib/txVerify.js
> +export function checkIsTxInProcess(coin, nonce = null) {
Move function to separate file. Rewrite to TS.

2023-12-14 10:59 UTC, adamant-al requested changes
We've chosen another approach.
See Feat: Decline second crypto transfer if we get same Nonce https://trello.com/c/HMtWwgV8

2023-12-29 16:52 UTC, closed without merging

2023-12-29 16:52 UTC, bludnic commented
Will be implemented in https://github.com/Adamant-im/adamant-im/pull/578