Feat/emogi in the input field
Adamant-im/adamant-im pull request #563
Opened 2023-11-18 19:46 UTC by juliahermak

![Screenshot 2023-11-18 19 43 31](https://github.com/Adamant-im/adamant-im/assets/122323015/8efee95d-4af9-4090-b36c-c38f3210f989)
![Screenshot 2023-11-18 19 43 48](https://github.com/Adamant-im/adamant-im/assets/122323015/7de078c2-d9cb-46ff-95f3-f26bd0f89f08)

2023-11-25 21:46 UTC, bludnic commented
![](https://github.trello.services/images/mini-trello-icon.png) [UI: Add emoji and move attach to the input field (copied from iOS)](https://trello.com/c/x5HC9Uyj/426-ui-add-emoji-and-move-attach-to-the-input-field-copied-from-ios)

2024-02-01 15:47 UTC, bludnic commented
@juliahermak Merge dev into current branch. Fix conflicts.

2024-02-11 04:39 UTC, bludnic requested changes

2024-02-11 04:39 UTC, bludnic commented on src/lib/display-mobile.js
> +}
Convert to .ts

2024-02-11 04:39 UTC, bludnic commented on src/components/AChat/AChatForm.vue
> +    })
Need to unsubscribe when component is unmounted

2024-02-11 06:52 UTC, bludnic approved these changes

2024-02-11 08:20 UTC, adamant-al commented on src/lib/display-mobile.js
> +  const displayMobile = window.innerWidth < 600
window.innerWidth < 450 or /Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent)

2024-02-11 19:46 UTC, bludnic requested changes

2024-02-11 19:46 UTC, bludnic commented on src/components/Chat/ChatEmojis.vue
> +import emojiPicker from '@/components/EmojiPicker.vue'
```suggestion
import EmojiPicker from '@/components/EmojiPicker.vue'
```

2024-02-12 22:51 UTC, bludnic requested changes

2024-02-12 22:51 UTC, bludnic commented on src/lib/display-mobile.ts
> +    /Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent)
Use `import { detect } from 'detect-browser'`. See example in components/Chat/Chat.vue

2024-02-25 11:42 UTC, adamant-al commented on src/lib/display-mobile.ts
> +import { detect } from 'detect-browser'
@bludnic @PaulDremanovich 
Let's choose a single function to check `isMobile`.
See https://github.com/Adamant-im/adamant-im/pull/601

2024-02-25 11:47 UTC, adamant-al commented on src/components/AChat/AChatForm.vue
> +      console.log('focus', this.$refs.messageTextarea)
Remove logging.

2024-02-26 16:15 UTC, merged