feat: Save texts in input fields—message drafts
Adamant-im/adamant-im pull request #564
Opened 2023-11-22 23:20 UTC by juliahermak

@adamant-al  Done

2023-11-23 12:33 UTC, adamant-al commented
One more thing, keep reply/quote state.

2023-11-25 21:46 UTC, bludnic commented
![](https://github.trello.services/images/mini-trello-icon.png) [Feat: Save texts in input fields—message drafts](https://trello.com/c/am4oBJ6s/263-feat-save-texts-in-input-fields-message-drafts)

2023-12-01 16:30 UTC, juliahermak commented
@adamant-al look now

2023-12-02 16:14 UTC, adamant-al approved these changes
Works well.
Looks good.

2023-12-03 05:15 UTC, juliahermak commented
Added.

2024-01-10 01:49 UTC, bludnic requested changes

2024-01-10 01:49 UTC, bludnic commented on src/components/Chat/Chat.vue
> +      this.replyMessageId = this.$store.getters['draftMessage/draftReplyTold'](this.partnerId)
```suggestion
   const draftMessage = this.$store.getters['draftMessage/draftReplyTold'](this.partnerId)
    if (draftMessage) {
      this.replyMessageId = draftMessage
```

2024-01-10 01:49 UTC, bludnic commented on src/components/Chat/Chat.vue
> +      this.$store.dispatch('draftMessage/deleteWhenSend', { partnerId: this.partnerId })
draftMessage/removeDraft
draftMessage/deleteDraft

2024-01-10 01:49 UTC, bludnic commented on src/store/types.ts
> +import { DraftState } from '@/store/modules/draft-message'
Enter

2024-01-10 01:49 UTC, bludnic commented on src/store/index.js
> +      dispatch('draftMessage/resetState', null, { root: true })
Delete

2024-01-10 01:49 UTC, bludnic commented on src/store/modules/draft-message/index.ts
> +  },
Delete

2024-01-10 02:59 UTC, bludnic approved these changes

2024-01-12 16:44 UTC, merged