feat: page with sound vibrations
Adamant-im/adamant-im pull request #579
Opened 2024-01-05 20:48 UTC by juliahermak

2024-01-05 21:43 UTC, juliahermak commented
![](https://github.trello.services/images/mini-trello-icon.png) [Feat: Vibro](https://trello.com/c/iudwekjv/406-feat-vibro)

2024-01-10 11:10 UTC, adamant-al requested changes
Short pauses don't feel like pauses.

2024-01-10 11:10 UTC, adamant-al commented on src/lib/vibrate.js
> +  DOUBLE_SHORT: [80, 40, 80]
```suggestion
  DOUBLE_VERY_SHORT: [40, 40, 40],
  TRIPLE_VERY_SHORT: [40, 40, 40, 40, 40],
  DOUBLE_SHORT: [80, 80, 80]
```

2024-01-17 17:59 UTC, adamant-al commented on src/lib/vibrate.js
> +  DOUBLE_SHORT: [80, 40, 80]
60 is the most suitable pause

2024-01-17 18:00 UTC, adamant-al commented
I'm OK to merge it.

2024-01-19 14:15 UTC, bludnic approved these changes

2024-01-19 14:15 UTC, merged