feat: translation zh.json and configure it in vue-i18n
Adamant-im/adamant-im pull request #582
Opened 2024-01-10 22:59 UTC by juliahermak

2024-01-10 23:53 UTC, juliahermak commented
![](https://github.trello.services/images/mini-trello-icon.png) [Translate the app to Chinese language](https://trello.com/c/ox0upUkP/481-translate-the-app-to-chinese-language)

2024-01-11 08:57 UTC, adamant-al requested changes

2024-01-11 08:57 UTC, adamant-al commented on src/locales/zh.json
> +      "welcome_message": "ADAMANT是一种独特的区块链信使，独立于政府、企业甚至其开发者。这是由于去中心化的网络、完全开放的源代码和用户的反馈。这就是为什么每一个动作，包括消息传递或保存新联系人，都要收取0.001 ADM的网络费用。\n\n与典型的P2P和集中式信使不同，区块链系统提供了卓越的安全性y和隐私。更重要的是，它为用户提供了新的可能性，例如在聊天中存储和
```suggestion
      "welcome_message": "ADAMANT是一种独特的区块链信使，独立于政府、企业甚至其开发者。这是由于去中心化的网络、完全开放的源代码和用户的反馈。这就是为什么每一个动作，包括消息传递或保存新联系人，都要收取0.001 ADM的网络费用。\n\n与典型的P2P和集中式信使不同，区块链系统提供了卓越的安全性y和隐私。更重要的是，它为用户提供了新的可能性，例如在聊天中存储和传输加密货币，并完全控制私钥；使用ADAMANT作为2FA解决方案，匿名交换加密货币，并押注比特币利率等。\n\nADAMANT区块链系统属于其用户。没有人可以控制、阻止、停用、限制或审查帐户。用户对其内容、消息、媒体以及使用信使的目标和意图承担全部责任。\n\nADAMANT是匿名的，您的IP甚至对合作伙伴都是隐藏的，Tor版本可供那些想将隐私提升到一个新水平的人使用。但请记住，你的安全和匿名取决于你。不要关注你收到的链接，否则你的IP可能会被泄露。在设备上设置密码。了解有关安全性和匿名性的更多信息，请访问https://adamant.im/staysecured/ \n\n请确保您已为此帐户保存了唯一的密码短语--注销并再次登录。把你的密码也写在纸上。只有*您对密码短语的安全负责*。它无法恢复。如果其他人得到了它，你的代币就会被盗，你的信件也会被泄露。把这件事看得最重要，就好像你钱包里的代币要花10亿美元一样。\n\n要立即开始发送消息，请在“帐户”选项卡上获得免费欢迎令牌。然后开始新的聊天并填写朋友的ADM地址。建议您仅通过ADAMANT个人共享ADM地址。\n\n在Internet上搜索ADAMANT机器人程序的地址。他们可以交换加密货币，接受对加密货币利率的押注，并实现愿望。",
```

2024-01-11 08:57 UTC, adamant-al commented on src/locales/zh.json
> +      "adelina": "你好，我是adelina。让我们愉快地交谈一下！我可以做很多事情，比如：\n-起草一封电子邮件或其他文章\n-编写Python代码\n-回答关于一组文档的问题\n-支持对话\n-一系列主题的导师\n-翻译语言\n-写诗\n-模拟电子游戏中的角色等等",
```suggestion
      "adelina": "你好，我是Adelina。让我们愉快地交谈一下！我可以做很多事情，比如：\n-起草一封电子邮件或其他文章\n-编写Python代码\n-回答关于一组文档的问题\n-支持对话\n-一系列主题的导师\n-翻译语言\n-写诗\n-模拟电子游戏中的角色等等",
```

2024-01-11 08:57 UTC, adamant-al commented on src/locales/zh.json
> +    "free_adm_btn": "释放adm令牌",
```suggestion
    "free_adm_btn": "释放ADM令牌",
```

2024-01-11 08:57 UTC, adamant-al commented on src/locales/zh.json
> +      "adm_nodes": "adm节点",
```suggestion
      "adm_nodes": "ADM节点",
```

2024-01-11 08:57 UTC, adamant-al commented on src/locales/zh.json
> +    "unsupported_reason_api_version": "api版本过期",
```suggestion
    "unsupported_reason_api_version": "API版本过期",
```

2024-01-11 08:57 UTC, adamant-al commented on src/locales/zh.json
> +    "send_on_enter_tooltip": "用enter发送消息，用Ctrl+enter换行",
```suggestion
    "send_on_enter_tooltip": "用Enter发送消息，用Ctrl+Enter换行",
```

2024-01-11 08:57 UTC, adamant-al commented on src/locales/zh.json
> +    "error_incorrect_address": "crypto｝钱包地址不正确",
```suggestion
    "error_incorrect_address": "{crypto｝钱包地址不正确",
```

2024-01-11 08:57 UTC, adamant-al commented on src/locales/zh.json
> +    "confirm_message": "确认将<b>amount｝｛crypto｝</b>转移到地址<span class=\"address-in-confirm\">{address}</span>.",
```suggestion
    "confirm_message": "确认将<b> {amount｝｛crypto｝</b>转移到地址<span class=\"address-in-confirm\">{address}</span>.",
```

2024-01-11 08:57 UTC, adamant-al commented on src/locales/zh.json
> +    "legacy_address_text": "此用户有一个旧的｛crypto｝钱包。他们必须登录Messenger，余额超过0.001 ADM才能更新｛crupto｝的钱包地址",
```suggestion
    "legacy_address_text": "此用户有一个旧的｛crypto｝钱包。他们必须登录Messenger，余额超过0.001 ADM才能更新｛crypto｝的钱包地址",
```

2024-01-11 08:57 UTC, adamant-al commented on src/locales/zh.json
> +    "to_name_label": "收件人｛name｝",
```suggestion
    "to_name_label": "收件人｛name｝",
```

2024-01-11 12:19 UTC, adamant-al commented on src/locales/zh.json
> +  "title": "英语",
```suggestion
  "title": "中文",
```

2024-01-11 17:40 UTC, bludnic commented on src/locales/zh.json
> +    "to_name_label": "收件人｛name｝",
Your suggestion is identical?

2024-01-11 17:47 UTC, adamant-al commented
@juliahermak 
Please check for mistakes like `｛crypto}` once more.

2024-01-11 18:12 UTC, adamant-al approved these changes

2024-01-11 21:13 UTC, juliahermak commented
@adamant-al I corrected all the wrong characters that I found.

2024-01-11 21:41 UTC, adamant-al commented
@juliahermak 
I think you are doing wrong with commas and { }.
In Chinese, punctuation symbols go with spaces as a single character.
So you better revert this commit.

2024-01-12 16:59 UTC, bludnic approved these changes

2024-01-12 17:05 UTC, bludnic commented
Chinese `{}` chars don't work when used as a variables like `{crypto}`, `{amount}`. So the chars were replaced by a regular `{}` (without spaces).

@adamant-al probably better to ask Chen. Can he make a suggestions in this PR?

2024-01-12 17:26 UTC, adamant-al commented
> Chinese `{}` chars don't work when used as a variables like `{crypto}`, `{amount}`. So the chars were replaced by a regular `{}` (without spaces).
> 
> @adamant-al probably better to ask Chen. Can he make a suggestions in this PR?

Not necessary to ask him.
Use regular { } and spaces around.

2024-01-12 17:50 UTC, merged