feat: ui fix
Adamant-im/adamant-im pull request #588
Opened 2024-01-20 05:54 UTC by juliahermak

Rename `Nodes list` to `Nodes and services`
Format the Nodes screen (screenshots in trello)
Make `Settings` icon on the Login screen not so bright  
![Screenshot 2024-01-20 05 53 52](https://github.com/Adamant-im/adamant-im/assets/122323015/c1720092-8d9d-49d7-bad8-93ef90d7bd5b)

2024-01-20 14:50 UTC, adamant-al commented
@juliahermak 
I've checked https://msg-adamant-pr-588.surge.sh/
And see no changes except 'Rename Nodes list to Nodes and services'

2024-01-24 06:18 UTC, bludnic requested changes

2024-01-24 06:18 UTC, bludnic commented on src/components/nodes/adm/AdmNodesTableItem.vue
> +    const type = () => props.node.type
```suggestion
    const type = computed(() => props.node.type)
```

Keep it reactive

2024-01-24 06:18 UTC, bludnic commented on src/components/nodes/coins/CoinNodesTableItem.vue
> +    const type = () => props.node.type
```suggestion
    const type = computed(() => props.node.type)
```

Keep it reactive

2024-01-24 06:18 UTC, bludnic commented on src/store/modules/nodes/nodes-mutations.js
> +    const node = [payload.type][payload.url]
```suggestion
    const node = state[payload.type][payload.url]
```

2024-01-24 06:18 UTC, bludnic commented on src/store/modules/nodes/nodes-plugin.js
> +      const selectedNodeType = payload.type()
payload.type is not a function, it's a string

```suggestion
      const selectedNodeType = payload.type
```

2024-01-24 06:18 UTC, bludnic commented on src/store/modules/nodes/nodes-plugin.js
> +      const selectedNodeType = payload.type()
```suggestion
      const selectedNodeType = payload.type
```

2024-01-24 16:09 UTC, juliahermak commented
@adamant-al  Try again because I can see all the changes.
![Screenshot 2024-01-24 16 06 50](https://github.com/Adamant-im/adamant-im/assets/122323015/72b4885c-7224-47f5-99ff-a408926b4ff5)

2024-01-24 19:29 UTC, adamant-al requested changes
- Make it syllable
<img width="488" alt="image" src="https://github.com/Adamant-im/adamant-im/assets/33592982/d7b72c4b-c635-422e-b282-6ce49db4d736">
- Make the same for ADM nodes
- Remember this part
<img width="598" alt="image" src="https://github.com/Adamant-im/adamant-im/assets/33592982/d40a7013-de89-4399-a386-0d47cac33be5">
- I see `Settings` icon same bright
<img width="242" alt="image" src="https://github.com/Adamant-im/adamant-im/assets/33592982/a3b38e51-e34c-4dcb-b85e-c393a77d3832">
<img width="242" alt="image" src="https://github.com/Adamant-im/adamant-im/assets/33592982/6eb4d1bb-fa9e-49b4-81b9-825515fad01a">

2024-01-27 20:29 UTC, bludnic commented
![](https://github.trello.services/images/mini-trello-icon.png) [Feat: Health check improvements](https://trello.com/c/Uhj8LOdD/456-feat-health-check-improvements)

2024-01-28 09:13 UTC, adamant-al commented
@juliahermak 

Please update this part also:

<img width="371" alt="Screenshot 2024-01-28 в 13 05 30" src="https://github.com/Adamant-im/adamant-im/assets/33592982/bb6ca67c-a546-47ce-838c-0ca94006cc7a">

- No line break between `213` and `ms` (&nbsp;)
- Make `ms` of text-explanation style (as node version)
- No line break between "cube" and height
- Format height: `38533731` ⟶ `38,533,731`. See the task for iOS as an example Feat: Change node height format https://trello.com/c/igvLgkVP

Check this style:

<img width="259" alt="image" src="https://github.com/Adamant-im/adamant-im/assets/33592982/eaa5000f-2454-4dd7-a308-ee0e0debc271">

Can we move `style="font-size: 12px; height: 12px; width: 12px;"` to styles?

Both for ADM and coin nodes.

2024-01-30 12:08 UTC, bludnic requested changes

2024-01-30 12:08 UTC, bludnic commented on src/components/nodes/adm/AdmNodesTableItem.vue
> +
to keep reactivity it must be wrapped in `computed()`

2024-01-30 12:08 UTC, bludnic commented on src/store/modules/nodes/nodes-plugin.js
> +    // todo mutation for coin nodes
to fix

2024-01-31 01:52 UTC, juliahermak commented
@adamant-al  We can't move style="font-size: 12px; height: 12px; width: 12px;" to the styles because these are styles from Vuetify. Are there any corrections?
![Screenshot 2024-01-31 01 19 49](https://github.com/Adamant-im/adamant-im/assets/122323015/4afb029c-2dbc-46da-94c6-da1b2a59003d)

2024-01-31 10:48 UTC, adamant-al requested changes
- `Unsupportedms` ⟶ `Unsupported`
- ms: `rgba(255, 255, 255)` ⟶ `rgba(255, 255, 255, 0.7)`
- interline spacing: make the same as for ADM nodes
- for node types: `margin-left: 12px;` ⟶ `margin-left: 0px;`. This field will be shorter.
- check light theme also (I didn't test it)

<img width="360" alt="Screenshot 2024-01-31 в 14 40 12" src="https://github.com/Adamant-im/adamant-im/assets/33592982/aec82b57-8695-4f0d-b65a-fb9ababc2359">

2024-01-31 10:48 UTC, adamant-al commented on src/components/nodes/coins/CoinNodesTableItem.vue
> +      const regex = url.value.match(/^(https:\/\/)?(.*?)\.adamant\.im$/)
It may be not only `adamant.im`, but any top-level domain.

2024-01-31 10:48 UTC, adamant-al commented on src/components/nodes/components/NodeLabel.vue
> +  margin-left: 12px;
Remove it, as checkboxes have enough enough right margin.

2024-01-31 21:58 UTC, juliahermak commented
@adamant-al  Looks good in two themes. Need to make some more changes?
![Screenshot 2024-01-31 20 49 09](https://github.com/Adamant-im/adamant-im/assets/122323015/99a7cab6-5af9-4298-8f0c-62f6f6d40ca0)

2024-02-01 09:19 UTC, adamant-al commented on src/components/nodes/components/NodeLabel.vue
> +  margin-left: 0px;
Is this line necessary?
`margin-left: 0px;` is not be default?

2024-02-01 09:33 UTC, adamant-al commented
@juliahermak 
Looks good, thank you.

Two more things:

- Add "Coin" header (same style as Host and Ping)
- Make this space smaller. Probably, remove `padding-right: 8px!important;` for the `Coin` specific column. I don't understand space between Coin and Host is wider then between Host and Ping.

<img width="423" alt="image" src="https://github.com/Adamant-im/adamant-im/assets/33592982/c590355b-7bb8-4a54-b29a-26c3e578af05">

2024-02-11 07:49 UTC, bludnic requested changes

2024-02-11 07:49 UTC, bludnic commented on src/components/nodes/NodesTable.vue
> +  checkbox: `${className}__checkbox `
```suggestion
  checkbox: `${className}__checkbox`
```

2024-02-11 07:49 UTC, bludnic commented on src/components/nodes/hooks/useNodeStatus.ts
> +      text: node.height.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ','),
Create a helper function `formatHeight()` in `src/components/nodes/utils`

2024-02-11 07:49 UTC, bludnic commented on src/components/nodes/hooks/useNodeStatus.ts
> +    online: node.ping + ' ',
```suggestion
    online: node.ping,
```

Is the space still required?

2024-02-11 07:49 UTC, bludnic commented on src/components/nodes/NodesTable.vue
> +      <div v-if="tab === 'adm'">
```suggestion
      <div v-else-if="tab === 'adm'">
```

2024-02-11 08:10 UTC, juliahermak commented on src/components/nodes/hooks/useNodeStatus.ts
> +    online: node.ping + ' ',
yes

2024-02-11 15:50 UTC, merged