fix: snackbar redesign
Adamant-im/adamant-im pull request #598
Opened 2024-02-14 01:11 UTC by juliahermak

![Screenshot 2024-02-14 01 01 33](https://github.com/Adamant-im/adamant-im/assets/122323015/604b5c1e-34d2-4ef4-980b-126404f0efe1)
![Screenshot 2024-02-14 01 00 29](https://github.com/Adamant-im/adamant-im/assets/122323015/9d660fd2-9bb9-4b14-a104-b7141f988d48)

2024-02-14 01:12 UTC, juliahermak commented
![](https://github.trello.services/images/mini-trello-icon.png) [UI: Snackbar redesign](https://trello.com/c/5fbmaWsK/507-ui-snackbar-redesign)

2024-02-14 05:54 UTC, bludnic requested changes

2024-02-14 05:54 UTC, bludnic commented on src/store/modules/snackbar/index.js
> +  variant: ''
Set default variant. Check the docs of vuetify

2024-02-18 07:24 UTC, adamant-al approved these changes

2024-02-25 09:31 UTC, adamant-al approved these changes

2024-02-26 16:21 UTC, bludnic approved these changes

2024-02-26 16:21 UTC, merged