fix: windows, ubuntu: emojiPicker glitches when opening
Adamant-im/adamant-im pull request #603
Opened 2024-03-06 08:35 UTC by PaulDremanovich

2024-03-06 08:37 UTC, PaulDremanovich commented
![](https://github.trello.services/images/mini-trello-icon.png) [UI: Add emoji and move attach to the input field (copied from iOS)](https://trello.com/c/x5HC9Uyj/426-ui-add-emoji-and-move-attach-to-the-input-field-copied-from-ios)

2024-03-06 19:13 UTC, bludnic requested changes

2024-03-06 19:13 UTC, bludnic commented on src/components/EmojiPicker.vue
> +.emoji-picker.is-dark {
try to use `.theme--dark {}` and `.theme--light {}`. See example: https://github.com/Adamant-im/adamant-im/blob/6c0b5cba4ec14593494bdc73ab75085069f111fb/src/components/PartnerInfo.vue#L143

2024-03-07 20:50 UTC, bludnic requested changes

2024-03-07 20:50 UTC, bludnic commented on src/components/EmojiPicker.vue
> +    border-color: map-get($adm-colors, 'light-theme-border');
This section must contain only common styles for both themes. Don't put here styles like: border-color, color and background-color, etc.

Move the `border-color` to `.v-theme--light {...}`

2024-03-07 20:50 UTC, bludnic commented on src/assets/styles/settings/_colors.scss
> +  'light-theme-border': rgba(0, 0, 0, var(--v-border-opacity))
Remove these color constants. Write them directly in EmojiPicker.vue

2024-03-09 20:59 UTC, adamant-al approved these changes

2024-03-09 21:08 UTC, bludnic requested changes

2024-03-09 21:08 UTC, bludnic commented on src/components/EmojiPicker.vue
> +    border-color: $dark-theme-border-color;
No need in defining a constant. It is used only in one place. Use the color value directly:

```suggestion
    border-color: rgba(map-get($shades, 'black'), var(--v-border-opacity))
```

2024-03-09 21:08 UTC, bludnic commented on src/components/EmojiPicker.vue
> +    border-color: $light-theme-border-color;
Move `border-color` to .v-theme--light

2024-03-12 14:20 UTC, bludnic approved these changes

2024-03-14 14:12 UTC, adamant-al commented
@bludnic Can we merge?
I want it in the current release.

2024-03-16 09:51 UTC, RealGoodProgrammer approved these changes

2024-03-16 09:52 UTC, merged