feat: preview image
Adamant-im/adamant-im pull request #615
Opened 2024-03-28 05:51 UTC by juliahermak

![Screenshot 2024-03-28 05 51 04](https://github.com/Adamant-im/adamant-im/assets/122323015/1ca8b75a-2baf-4fe8-b859-f6cf7b72fffe)

2024-03-30 02:38 UTC, juliahermak commented
![](https://github.trello.services/images/mini-trello-icon.png) [Feat: Preview image and file](https://trello.com/c/X2LewT0P/528-feat-preview-image-and-file)

2024-04-10 21:48 UTC, bludnic requested changes

2024-04-10 21:48 UTC, bludnic commented on src/components/AChat/AChat.vue
> +      type: [Array, null],
remove 
```suggestion
      type: Array,
```

2024-04-10 21:48 UTC, bludnic commented on src/components/AChat/AChat.vue
> +      type: [Array, null],
rename the props to `files`

2024-04-10 21:48 UTC, bludnic commented on src/components/AChat/AChatPreviewFile.vue
> +      type: [Array, null],
```suggestion
      type: Array,
```

2024-04-10 21:48 UTC, bludnic commented on src/components/Chat/Chat.vue
> +      if (this.selectedImage.length < 10) {
Move `10` to constants.ts

2024-04-10 21:48 UTC, bludnic commented on src/components/Chat/Chat.vue
> +      if (this.selectedImage.length < 10) {
`export const UPLOAD_MAX_FILE_COUNT = 10`

2024-04-10 21:50 UTC, bludnic commented on src/components/Chat/Chat.vue
> +        alert('можно загрузить только 10 файлов')
Instead show a snackbar with the message: You can upload max N files

2024-05-07 23:11 UTC, bludnic commented
Closed because of incorrect branch name. Use this PR instead https://github.com/Adamant-im/adamant-im/pull/628

2024-05-07 23:11 UTC, closed without merging