Feat/service tab
Adamant-im/adamant-im pull request #630
Opened 2024-05-29 18:29 UTC by RealGoodProgrammer

![image](https://github.com/Adamant-im/adamant-im/assets/39791681/56faea76-3bed-4e47-ac26-98479ec2ed5f)

2024-05-30 14:20 UTC, bludnic requested changes

2024-05-30 14:20 UTC, bludnic commented on src/components/nodes/components/NodesTableHead.vue
> +      </th>
```suggestion
      <th :class="classes.label" class="pl-0 pr-2" v-if="!hideLabel">
        {{ label }}
      </th>
```

1. Rename prop to `label`
2. Pass it already translated, e.g. `<NodesTableHead :label="$t('nodes.service')" />`
3. Pass the label explicitly for "ADM" and "Coins tab", e.g. `<NodesTableHead :label="$t('nodes.coin')" />`

2024-05-30 14:20 UTC, bludnic commented on src/store/modules/rate/rate-actions.ts
> +  },
There no need in wrapping in `new Promise()`.

1. Prefix function with `async`

2. Use as:

```js
const { result, success } = await rateInfoClient.getAllRates()
if (success) {
  commit('setRates', result)
}
```

2024-05-30 14:20 UTC, bludnic commented on src/store/modules/rate/rate-actions.ts
> +  },
Similar for `getHistoryRates`

2024-05-30 14:20 UTC, bludnic commented on src/store/modules/rate/rate-mutations.ts
> +  loadRates(state) {
Use better name, e.g. `setLoaded`.

2024-05-30 14:20 UTC, bludnic commented on src/store/modules/services/services-mutations.ts
> +  toggle(state, payload: { type: AvailableService; url: string; active: boolean }) {
I'd suggest to define types for payload on the top of file.

type TogglePayload = { type: AvailableService; url: string; active: boolean }

2024-05-30 14:20 UTC, bludnic commented on src/store/modules/services/services-mutations.ts
> +    }: { serviceType: AvailableService; status: { url: string; active: boolean } }
Move type at the top of the file `type StatusPayload`. See previous comment.

2024-07-12 21:24 UTC, bludnic commented on src/lib/nodes/services.ts
> +  'rates-info': rateInfoClient
```suggestion
  ratesInfo: rateInfoClient
```

Better to follow same camelCase style

2024-07-13 18:11 UTC, PaulDremanovich approved these changes

2024-07-13 20:57 UTC, bludnic requested changes

2024-07-13 20:57 UTC, bludnic commented on src/lib/nodes/rate-info-service/RateInfoService.ts
> +}
These types belong to `RateInfoClient`. Move them to `/lib/nodes/rate-info-service/types/`

2024-07-13 20:57 UTC, bludnic commented on src/components/nodes/services/ServiceNodesTableItem.vue
> +import type { TNodeLabel } from '@/lib/nodes/constants.ts'
Remove `.ts` extension from imports. Check other files as well.

2024-07-13 20:57 UTC, bludnic commented on src/components/nodes/services/ServiceNodesTableItem.vue
> +import type { TNodeLabel } from '@/lib/nodes/constants.ts'
Use relative import where possible.

2024-07-13 20:57 UTC, bludnic commented on src/lib/nodes/rate-info-service/RateInfoClient.ts
> +    const node = await this.fetchNode()
I think you can reuse `getNode()` from parent class and remove `async fetchNode()` below.

```suggestion
    const node = this.getNode()
```

2024-07-13 20:57 UTC, bludnic commented on src/lib/nodes/rate-info-service/RateInfoClient.ts
> +    const node = await this.fetchNode()
Check the comment above

```suggestion
    const node = this.getNode()
```

2024-07-13 20:57 UTC, bludnic commented on src/lib/nodes/rate-info-service/RateInfoService.ts
> +      `/getHistory?timestamp=${timestamp}`
Pass query params using axios `params` prop. Add TS type `type GetHistoryParams`

2024-07-15 14:04 UTC, bludnic requested changes

2024-07-15 14:04 UTC, bludnic commented on src/store/modules/services/services-plugin.ts
> +export default (store: Store<ServicesState>) => {
```ts
import { Plugin } from 'vuex'

export default const servicesPlugin: Plugin<ServicesState> = (store) => ...
```

2024-07-16 17:58 UTC, PaulDremanovich commented
![](https://github.trello.services/images/mini-trello-icon.png) [Add health check for indexers](https://trello.com/c/DDOcYSIx/496-add-health-check-for-indexers)

2024-07-17 01:13 UTC, bludnic commented
![](https://github.trello.services/images/mini-trello-icon.png) [Add infoService health check](https://trello.com/c/tpbSZXFE/482-add-infoservice-health-check)

2024-08-01 04:40 UTC, bludnic approved these changes

2024-08-01 04:40 UTC, merged