Feat/support kly qrcode
Adamant-im/adamant-im pull request #674
Opened 2024-10-22 09:12 UTC by NikIvv

Read QR from an image file created in Klayr wallet.

2024-10-22 19:15 UTC, bludnic requested changes

2024-10-22 19:15 UTC, bludnic commented on src/components/SendFundsForm.vue
>        const recipient = parseURIasAIP(uri)
I suggest to create a separate function for parsing KLY based URIs. For example:

```ts
function parseKlyURI(uri: string) {
  // ...
  return { address, amount,  }
}
```

Then you can create a function that will unify the result of both parsers:

```ts
function parseURI() {
  if (isKlyUri) {
    return parseKlyURI()
  }

  return parseURIasAIP() // ADM based URI
}
```

2024-10-22 19:16 UTC, bludnic commented
![](https://github.trello.services/images/mini-trello-icon.png) [UI: Style "No active ADM nodes" dialog](https://trello.com/c/FKPdukTm/606-ui-style-no-active-adm-nodes-dialog)

2024-10-22 19:16 UTC, bludnic commented
![](https://github.trello.services/images/mini-trello-icon.png) [Feat: Enable KLY QR codes from their official app (copied from iOS)](https://trello.com/c/PPllsFpR/603-feat-enable-kly-qr-codes-from-their-official-app-copied-from-ios)

2024-10-23 15:35 UTC, bludnic commented on src/lib/uri.js
> + * @param {string} URI's query parameters
There is only one param `parseURIasAIP(uri)`

2024-10-23 16:59 UTC, NikIvv commented on src/lib/uri.js
> +}
This change, in turn, make us to do further changes (not big ones) in parseURIasAIP(). If we need to get rid of formQueryParamsObject function completely, I'll do that. Please confirm.

2024-10-24 07:17 UTC, bludnic commented on src/lib/uri.js
> +}
You can transform `paramsFromUrl` into an object so it should behave as the previous implementation. Or, is there something else I miss?

2024-10-24 07:20 UTC, bludnic commented on src/lib/uri.js
> +  return { address, crypto: Cryptos.KLY, params, protocol: Cryptos.KLY }
Cryptos.KLY -> Cryptos.KLY.toLowerCase()

2024-10-24 13:07 UTC, bludnic approved these changes

2024-10-25 11:00 UTC, merged