feat/open-in-explorer-for-wallets-on-account-screen
Adamant-im/adamant-im pull request #695
Opened 2024-12-16 06:57 UTC by NikIvv

2024-12-16 07:01 UTC, NikIvv commented
Some notes on the current implementations: explorer.btc.com was not accessible during my testing; removed 'Open In Explorer' menu option for USDT and USDC as they have not been described in configs.

2024-12-16 20:11 UTC, bludnic requested changes

2024-12-16 20:11 UTC, bludnic commented on src/components/ShareURIDialog.vue
> +      window.open(explorerLink, '_blank', 'resizable,scrollbars,status,noopener')
You can use [getExplorerAddressUrl](https://github.com/Adamant-im/adamant-im/blob/eacc2d3fd8c6a3a14dd532f5d560783f4d56a967/src/config/utils/getExplorerAddressUrl.ts) helper:

1. No need in `websiteUriToOnion`. Tor has a separate [config](https://github.com/Adamant-im/adamant-im/blob/658efd2b068473745615f6dfe4e4b097e62c4c27/src/config/tor.json#L51) which is automatically replaced when building the app.
2. Use [isErc20](https://github.com/Adamant-im/adamant-im/blob/e0a8fdb2980e6e85013726826f9d33dea3f0a668/src/lib/constants/index.js#L80) helper to detect ETH based crypto.

2024-12-16 20:11 UTC, bludnic commented on src/components/ShareURIDialog.vue
> +            v-if="crypto !== cryptos.USDT && crypto !== cryptos.USDC"
You don't need this. See comment below (`isErc20` helper)

2024-12-16 20:11 UTC, bludnic commented on src/components/ShareURIDialog.vue
> +    cryptos: Cryptos
You probably don't need this anymore

2024-12-16 20:11 UTC, bludnic commented on src/components/ShareURIDialog.vue
>  <script>
After fixing the issues, I suggest you to do a little refactor by rewriting the component using Composition API and TypeScript. Follow the guidelines https://developers.adamant.im/template-classes.html

2024-12-23 06:57 UTC, bludnic commented on src/components/ShareURIDialog.vue
> +      window.open(explorerLink, '_blank', 'resizable,scrollbars,status,noopener')
We build the app for Tor using [tor.json](https://github.com/Adamant-im/adamant-im/blob/eacc2d3fd8c6a3a14dd532f5d560783f4d56a967/src/config/tor.json#L30) config, so the `getExplorerAddressUrl()` will choose the right URL automatically.

2024-12-26 20:15 UTC, bludnic commented
> Some notes on the current implementations: explorer.btc.com was not accessible during my testing; removed 'Open In Explorer' menu option for USDT and USDC as they have not been described in configs.

@NikIvv Bitcoin explorer was replaced in https://github.com/Adamant-im/adamant-wallets/pull/101
We will include these changes in the next release.

2024-12-26 20:21 UTC, bludnic commented on src/components/ShareURIDialog.vue
> +          <v-list-item v-if="!isErc" @click="openInExplorer">
ERC20 tokens also have an address (same as for ETH).
Handle that logic in the `openInExplorer` method.

2024-12-28 17:58 UTC, bludnic approved these changes

2024-12-28 17:58 UTC, merged